version: '3.9'

services:
  app:
    container_name: ecosystems-simulations
    image: ecosystems-simulations
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
